"""The map is plain data too, independent of any renderer.

A tile is just a character for now ('#' wall, '.' floor). Later this can grow
into a Tile dataclass (walkable, transparent, colours) without touching the
render path.
"""
import heapq
from collections import deque

# The habitable land is a fixed-size island; a "world" map that is comfortably
# larger than this gets the land dropped in its centre and the rest flooded into
# open ocean (see ``world_land_rect``). Small maps (tests, legacy plain rooms)
# stay a single walled room.
LAND_WIDTH = 120
LAND_HEIGHT = 60

# Archipelago layout (a scale-test world): the *same* 120x60 island the single-world
# map builds, replicated across a grid so the simulation runs many copies at once.
# Every cell holds a full island -- the default houses and the two lakes and river --
# generated by the same carve helpers as the lone island, then populated with its own
# village and wildlife by worldgen. Unlike the lone island there is no water coastline
# ring: each island is solid floor to its edge. There is no wall border anywhere
# either; the whole map is open sea with the islands dropped in, an OCEAN_GAP-wide
# channel of water between neighbours (and half that inset from the map edge).
# Selected explicitly via ``GameMap(..., layout="islands")`` (never inferred from size).
ARCHIPELAGO_GRID = 10  # ARCHIPELAGO_GRID**2 islands (10x10 = 100)
OCEAN_GAP = 20  # open-sea channel between adjacent island cells
_CELL_W = LAND_WIDTH + OCEAN_GAP
_CELL_H = LAND_HEIGHT + OCEAN_GAP
ARCHIPELAGO_WIDTH = _CELL_W * ARCHIPELAGO_GRID
ARCHIPELAGO_HEIGHT = _CELL_H * ARCHIPELAGO_GRID


def world_land_rect(width: int, height: int) -> tuple[int, int, int, int] | None:
    """The centred land rectangle for a world map, or ``None`` for a map too
    small to be the ocean world. A map at least twice the land in each dimension
    is treated as the world (land island ringed by a vast ocean); anything
    smaller is a plain walled room, so tiny test maps keep the classic layout."""
    if width >= 2 * LAND_WIDTH and height >= 2 * LAND_HEIGHT:
        return ((width - LAND_WIDTH) // 2, (height - LAND_HEIGHT) // 2, LAND_WIDTH, LAND_HEIGHT)
    return None


class GameMap:
    WALL = "#"
    FLOOR = "."
    WATER = "~"
    DOOR = "+"  # passable + transparent gap in a wall; marks a house entrance
    WINDOW = "o"  # blocks movement but is transparent (see-through) like a wall gap

    def __init__(
        self,
        width: int,
        height: int,
        *,
        land_rect: tuple[int, int, int, int] | None | str = "auto",
        layout: str = "auto",
    ):
        self.width = width
        self.height = height
        # ``layout`` records how the map was built so a save can reconstruct the
        # same world from size alone (see persistence). "auto" is the classic
        # room/single-island rule below; "islands" is the archipelago grid.
        self.layout = layout
        # True for the archipelago: many islands in open sea, no wall border. Off
        # for the walled room / single-island world.
        self.is_archipelago = False
        # Grid geometry (cell_w, cell_h, inset_x, inset_y, land_w, land_h) for the
        # O(1) ``is_ocean`` test; only set on the archipelago.
        self._island_grid: tuple[int, int, int, int, int, int] | None = None
        # ``revision`` bumps whenever a tile changes at runtime (building a wall,
        # a door, ...). Cache holders (the renderer's map surface, house
        # detection, connected-region labels) compare it to know when to rebuild.
        self.revision = 0
        # Connected-region labels are cached PER ISLAND, not for the whole map:
        # islands are separated by open water, so a walkable component never spans
        # two of them. Each island's labels are rebuilt only when a tile edit lands
        # on THAT island (tracked by ``_island_edit_rev``), so an NPC raising a wall
        # on one island doesn't force a re-flood of all 100 (the whole-map recompute
        # was the dominant per-turn cost at archipelago scale). ``region_of`` returns
        # ``island_index * _REGION_ID_STRIDE + local_id`` so ids stay globally unique.
        self._island_region_cache: dict[int, dict[tuple[int, int], int]] = {}
        self._island_region_rev: dict[int, int] = {}
        self._island_edit_rev: dict[int, int] = {}
        # Enclosed-room (house) detection is likewise cached per island and rebuilt
        # only for an edited island (see ``enclosed_rooms``), instead of re-flooding
        # every island's floor whenever one tile changes anywhere.
        self._island_rooms_cache: dict[int, list[frozenset[tuple[int, int]]]] = {}
        self._island_rooms_rev: dict[int, int] = {}
        # Memoised concatenation of every island's rooms; the same object is handed
        # back until some island's rooms are rebuilt (callers rely on that identity).
        self._all_rooms_cache: list[frozenset[tuple[int, int]]] | None = None
        # Tiles changed since the renderer last refreshed its cached map surface.
        # The renderer consumes these to repaint just the changed cells instead
        # of re-rendering the whole (large) world surface on every edit.
        self._dirty_tiles: set[tuple[int, int]] = set()
        # Per-120x60-region edit counters (mirrors the simulation-region grid in
        # regions.py, kept independent here to avoid a circular import). Lets a
        # pathfinding cache invalidate only around an edit that actually
        # touched its region, instead of on any edit anywhere in the world.
        self._region_edit_revision: dict[tuple[int, int], int] = {}

        if layout == "islands":
            self._build_islands()
            return

        # ``land_rect="auto"`` (the default) lets a big enough map become the
        # ocean world automatically -- so a map loaded from a save reconstructs
        # the same island without the save needing to record the layout. Pass an
        # explicit rect to force it, or ``None`` to force a plain walled room.
        if land_rect == "auto":
            land_rect = world_land_rect(width, height)

        if land_rect is None:
            # Classic single room: walls around the edge, floor inside. The whole
            # map is "land".
            self.land_x0, self.land_y0 = 0, 0
            self.land_w, self.land_h = width, height
            self.has_ocean = False
            self.tiles = [
                [
                    self.WALL
                    if x == 0 or y == 0 or x == width - 1 or y == height - 1
                    else self.FLOOR
                    for x in range(width)
                ]
                for y in range(height)
            ]
        else:
            # An island in a vast ocean: everything is water except the central
            # land rectangle, whose own edge is a water coastline (so the land is
            # bounded by sea, not a wall). Only the map's outermost ring stays
            # wall, a hard boundary far out at the edge of the world.
            lx, ly, lw, lh = land_rect  # type: ignore[misc]
            self.land_x0, self.land_y0 = lx, ly
            self.land_w, self.land_h = lw, lh
            self.has_ocean = True
            self.tiles = [[self.WATER for _ in range(width)] for _ in range(height)]
            for x in range(width):
                self.tiles[0][x] = self.WALL
                self.tiles[height - 1][x] = self.WALL
            for y in range(height):
                self.tiles[y][0] = self.WALL
                self.tiles[y][width - 1] = self.WALL
            for y in range(ly, ly + lh):
                for x in range(lx, lx + lw):
                    on_coast = x in (lx, lx + lw - 1) or y in (ly, ly + lh - 1)
                    self.tiles[y][x] = self.WATER if on_coast else self.FLOOR

        # A single-island (or plain-room) map is a one-entry archipelago: worldgen
        # loops ``islands`` uniformly, and ``land_area`` scales the flora budget.
        self.islands = [(self.land_x0, self.land_y0, self.land_w, self.land_h)]
        self.land_area = self.land_w * self.land_h
        self._add_default_buildings()
        self._add_water_features()

    def _build_islands(self) -> None:
        """Tile the classic 120x60 island across an ``ARCHIPELAGO_GRID`` x
        ``ARCHIPELAGO_GRID`` grid, each island generated by the same building / lake /
        river carve as the lone island (just offset to its cell), but as solid floor
        with no water coastline ring. The map is otherwise open sea -- no wall border,
        an ``OCEAN_GAP`` channel of water between islands -- so every island is fully
        surrounded by ocean. Records each island's land rect in ``self.islands`` for
        worldgen to populate."""
        self.is_archipelago = True
        self.has_ocean = True
        self.tiles = [[self.WATER for _ in range(self.width)] for _ in range(self.height)]

        inset = OCEAN_GAP // 2
        # Grid geometry kept for the O(1) ``is_ocean`` test (which cell owns a tile).
        self._island_grid = (_CELL_W, _CELL_H, inset, inset, LAND_WIDTH, LAND_HEIGHT)
        # Derive the grid from the actual map size (whole cells that fit) rather than
        # assuming the config size, so a map built at any dimension -- e.g. an older
        # save's -- tiles cleanly and never carves past its bounds.
        cols = max(1, self.width // _CELL_W)
        rows = max(1, self.height // _CELL_H)
        self.islands = []
        for j in range(rows):
            for i in range(cols):
                lx = i * _CELL_W + inset
                ly = j * _CELL_H + inset
                rect = (lx, ly, LAND_WIDTH, LAND_HEIGHT)
                self._carve_island(*rect)
                self._add_default_buildings(rect)
                self._add_water_features(rect)
                self.islands.append(rect)

        # ``land_*`` points at the first island so back-compat readers still see a
        # valid land rect; ``land_area`` is the whole archipelago's land for scaling.
        self.land_x0, self.land_y0, self.land_w, self.land_h = self.islands[0]
        self.land_area = sum(w * h for _x, _y, w, h in self.islands)

    def _carve_island(self, lx: int, ly: int, lw: int, lh: int) -> None:
        """Lay one island of solid floor into the open sea. Unlike the lone-island
        world, there is no water coastline ring around the land -- the island is
        walkable right to its edge, with open water only in the ``OCEAN_GAP`` channel
        between islands (lakes/river are still carved into the interior afterwards)."""
        for y in range(ly, ly + lh):
            row = self.tiles[y]
            for x in range(lx, lx + lw):
                row[x] = self.FLOOR

    def _carve_building(
        self,
        left: int,
        top: int,
        right: int,
        bottom: int,
        door: tuple[int, int],
    ) -> None:
        if not self.in_bounds(left, top) or not self.in_bounds(right, bottom):
            return
        if right - left < 2 or bottom - top < 2:
            return

        for y in range(top, bottom + 1):
            for x in range(left, right + 1):
                is_edge = x in {left, right} or y in {top, bottom}
                self.tiles[y][x] = self.WALL if is_edge else self.FLOOR

        door_x, door_y = door
        if self.in_bounds(door_x, door_y):
            self.tiles[door_y][door_x] = self.DOOR

    def _land_rect(self, rect: tuple[int, int, int, int] | None) -> tuple[int, int, int, int]:
        """The land rectangle to operate on: an explicit one (per-island, for the
        archipelago) or the map's primary land rect (the lone-island / room case)."""
        return rect if rect is not None else (self.land_x0, self.land_y0, self.land_w, self.land_h)

    def _add_default_buildings(self, rect: tuple[int, int, int, int] | None = None) -> None:
        lx, ly, lw, lh = self._land_rect(rect)
        if lw < 30 or lh < 16:
            return

        land_right = lx + lw
        self._carve_building(left=lx + 4, top=ly + 3, right=lx + 12, bottom=ly + 8, door=(lx + 8, ly + 8))
        self._carve_building(
            left=land_right - 14,
            top=ly + 5,
            right=land_right - 5,
            bottom=ly + 11,
            door=(land_right - 10, ly + 11),
        )

    def _spawn_safe_zone(self, rect: tuple[int, int, int, int] | None = None) -> tuple[int, int, int, int]:
        """A rectangle around a land centre kept clear of water so a spawn there
        (the player, on their island) never starts stuck in a lake or river.
        Returns (min_x, min_y, max_x, max_y)."""
        lx, ly, lw, lh = self._land_rect(rect)
        cx = lx + lw // 2
        cy = ly + lh // 2
        return (cx - 6, cy - 4, cx + 6, cy + 4)

    def _carve_lake(self, cx: int, cy: int, rx: int, ry: int, rect: tuple[int, int, int, int] | None = None) -> None:
        """Flood an ellipse of interior floor into water, clipped to one island."""
        lx, ly, lw, lh = self._land_rect(rect)
        sx0, sy0, sx1, sy1 = self._spawn_safe_zone(rect)
        y_lo = max(ly + 1, cy - ry)
        y_hi = min(ly + lh - 1, cy + ry + 1)
        x_lo = max(lx + 1, cx - rx)
        x_hi = min(lx + lw - 1, cx + rx + 1)
        for y in range(y_lo, y_hi):
            for x in range(x_lo, x_hi):
                if sx0 <= x <= sx1 and sy0 <= y <= sy1:
                    continue
                nx = (x - cx) / max(1, rx)
                ny = (y - cy) / max(1, ry)
                if nx * nx + ny * ny <= 1.0 and self.tiles[y][x] == self.FLOOR:
                    self.tiles[y][x] = self.WATER

    def _carve_river(self, start_x: int, width: int = 2, rect: tuple[int, int, int, int] | None = None) -> None:
        """Carve a gently wavering vertical river down one island, skipping its
        central spawn zone so it never seals a spawn in."""
        lx, ly, lw, lh = self._land_rect(rect)
        sx0, sy0, sx1, sy1 = self._spawn_safe_zone(rect)
        x = start_x
        for y in range(ly + 1, ly + lh - 1):
            # Deterministic gentle meander (no RNG so maps stay reproducible).
            if (y // 3) % 2 == 0:
                x += 1
            else:
                x -= 1
            x = max(lx + 2, min(lx + lw - 3, x))
            for wx in range(x, x + width):
                if sx0 <= wx <= sx1 and sy0 <= y <= sy1:
                    continue
                if self.in_bounds(wx, y) and self.tiles[y][wx] == self.FLOOR:
                    self.tiles[y][wx] = self.WATER

    def _add_water_features(self, rect: tuple[int, int, int, int] | None = None) -> None:
        lx, ly, lw, lh = self._land_rect(rect)
        if lw < 24 or lh < 14:
            return
        self._carve_lake(cx=lx + int(lw * 0.22), cy=ly + int(lh * 0.72), rx=6, ry=4, rect=(lx, ly, lw, lh))
        self._carve_lake(cx=lx + int(lw * 0.80), cy=ly + int(lh * 0.28), rx=7, ry=5, rect=(lx, ly, lw, lh))
        self._carve_river(start_x=lx + int(lw * 0.62), rect=(lx, ly, lw, lh))

    def clear_water_around(self, x: int, y: int, radius: int = 1) -> None:
        """Turn any water in a square around (x, y) back into floor. Used as a
        final safety so an entity (the player) is never spawned onto water."""
        for ny in range(y - radius, y + radius + 1):
            for nx in range(x - radius, x + radius + 1):
                if self.in_bounds(nx, ny) and self.tiles[ny][nx] == self.WATER:
                    self.tiles[ny][nx] = self.FLOOR

    def in_bounds(self, x: int, y: int) -> bool:
        return 0 <= x < self.width and 0 <= y < self.height

    def is_walkable(self, x: int, y: int) -> bool:
        # Walls, water, and windows all block movement; a door is a passable gap.
        # Water/windows stay transparent to sight (has_line_of_sight only blocks
        # on walls).
        return self.in_bounds(x, y) and self.tiles[y][x] not in (self.WALL, self.WATER, self.WINDOW)

    def is_water(self, x: int, y: int) -> bool:
        return self.in_bounds(x, y) and self.tiles[y][x] == self.WATER

    def is_ocean(self, x: int, y: int) -> bool:
        """A water tile out in the open sea -- water that lies outside the central
        land rectangle. This is where seaweed grows and fish roam; interior lakes
        and the coastline ring around the land do not count."""
        if not self.is_water(x, y):
            return False
        if self._island_grid is not None:
            # Archipelago: ocean is any water outside every island's land rect (the
            # channels between islands and the open border), computed in O(1) from
            # the regular grid -- a tile's owning cell is the only one it can be in.
            cell_w, cell_h, inset_x, inset_y, land_w, land_h = self._island_grid
            ox = x - (x // cell_w) * cell_w - inset_x
            oy = y - (y // cell_h) * cell_h - inset_y
            inside_island = 0 <= ox < land_w and 0 <= oy < land_h
            return not inside_island
        return not (
            self.land_x0 <= x < self.land_x0 + self.land_w
            and self.land_y0 <= y < self.land_y0 + self.land_h
        )

    def is_passable(self, x: int, y: int) -> bool:
        """Can a *swimming* actor (the player) move here? Everything but walls and
        windows, including water and doors. NPC pathfinding still uses
        ``is_walkable`` (land only), so animals stay ashore while the player can
        wade in to swim."""
        return self.in_bounds(x, y) and self.tiles[y][x] not in (self.WALL, self.WINDOW)

    def tile_at(self, x: int, y: int) -> str:
        return self.tiles[y][x]

    def set_tile(self, x: int, y: int, tile: str) -> bool:
        """Change a tile at runtime (building/clearing). Never overwrites the map
        border. Bumps ``revision`` on a real change so caches rebuild. Returns
        True when a change was applied."""
        if not self.in_bounds(x, y):
            return False
        if x == 0 or y == 0 or x == self.width - 1 or y == self.height - 1:
            return False  # keep the world border intact
        if self.tiles[y][x] == tile:
            return False
        self.tiles[y][x] = tile
        self.revision += 1
        self._dirty_tiles.add((x, y))
        region = self._edit_region_of(x, y)
        self._region_edit_revision[region] = self._region_edit_revision.get(region, 0) + 1
        # Invalidate only the edited island's connected-region cache (see region_of).
        island = self._island_index_of(x, y)
        if island is not None:
            self._island_edit_rev[island] = self._island_edit_rev.get(island, 0) + 1
        return True

    def _edit_region_of(self, x: int, y: int) -> tuple[int, int]:
        """The same coarse 120x60 grid cell ``regions.region_at`` would report
        for ``(x, y)``, computed locally (see ``_region_edit_revision``)."""
        area_w = max(1, min(LAND_WIDTH, self.width))
        area_h = max(1, min(LAND_HEIGHT, self.height))
        cols = max(1, self.width // area_w)
        rows = max(1, self.height // area_h)
        return (min(cols - 1, max(0, x // area_w)), min(rows - 1, max(0, y // area_h)))

    def region_edit_revision(self, x: int, y: int) -> int:
        """How many tile edits have landed in ``(x, y)``'s 120x60 region.
        A pathfinding cache scoped to that region can compare this over time
        to know when a *nearby* edit (not just any edit anywhere) invalidates
        it."""
        return self._region_edit_revision.get(self._edit_region_of(x, y), 0)

    def distance_field(self, goal: tuple[int, int]) -> dict[tuple[int, int], int]:
        """BFS distance (8-directional steps) from ``goal`` to every walkable
        tile that can reach it -- i.e. "how far is this tile from goal" for a
        whole region, computed once. Ignores dynamic occupants, same as
        ``find_path`` (a mover re-checks its immediate next step against live
        occupants before committing). A caller can reuse this "flow field" for
        many turns and many travellers: from any current position, stepping to
        the neighbour with the smallest value here always makes progress
        toward ``goal``, without a fresh pathfind."""
        gx, gy = goal
        width, height, tiles = self.width, self.height, self.tiles
        WALL, WATER, WINDOW = self.WALL, self.WATER, self.WINDOW
        if not (0 <= gx < width and 0 <= gy < height):
            return {}
        if tiles[gy][gx] == WALL or tiles[gy][gx] == WATER or tiles[gy][gx] == WINDOW:
            return {}
        # The neighbour scan, bounds test and walkability test are inlined (rather
        # than going through neighbors_8/is_walkable) because this is a hot BFS loop
        # -- it avoids building a fresh candidate list and two method calls per tile.
        distances: dict[tuple[int, int], int] = {goal: 0}
        queue: deque[tuple[int, int]] = deque([goal])
        while queue:
            cx, cy = queue.popleft()
            nd = distances[(cx, cy)] + 1
            for nx, ny in (
                (cx + 1, cy), (cx - 1, cy), (cx, cy + 1), (cx, cy - 1),
                (cx + 1, cy + 1), (cx + 1, cy - 1), (cx - 1, cy + 1), (cx - 1, cy - 1),
            ):
                if not (0 <= nx < width and 0 <= ny < height):
                    continue
                t = tiles[ny][nx]
                if t == WALL or t == WATER or t == WINDOW:
                    continue
                nxt = (nx, ny)
                if nxt in distances:
                    continue
                distances[nxt] = nd
                queue.append(nxt)
        return distances

    def consume_dirty_tiles(self) -> set[tuple[int, int]]:
        """Return (and clear) the tiles edited since the last call. The renderer
        uses this to repaint just the changed cells of its cached map surface
        rather than re-rendering the whole world on every edit."""
        dirty = self._dirty_tiles
        self._dirty_tiles = set()
        return dirty

    # region_of ids are ``island_index * _REGION_ID_STRIDE + local_label``. The
    # stride just has to exceed the most connected components one island can hold
    # (a handful), with plenty of headroom.
    _REGION_ID_STRIDE = 1_000_000

    def _island_index_of(self, x: int, y: int) -> int | None:
        """Which island's land rect owns ``(x, y)``, or ``None`` for a tile in open
        water between islands. O(1) on the archipelago via the regular grid; the
        single-island / room world is one island (index 0) covering the whole map."""
        grid = self._island_grid
        if grid is None:
            return 0 if self.in_bounds(x, y) else None
        cell_w, cell_h, inset_x, inset_y, land_w, land_h = grid
        i, j = x // cell_w, y // cell_h
        ox = x - i * cell_w - inset_x
        oy = y - j * cell_h - inset_y
        if 0 <= ox < land_w and 0 <= oy < land_h:
            return j * (self.width // cell_w) + i
        return None

    def _compute_island_regions(self, island: int) -> dict[tuple[int, int], int]:
        """Label the walkable tiles of ONE island with connected-region ids
        (8-connectivity, matching ``find_path``), flood-filling only within that
        island's land rect. Two tiles share a label iff a walking path connects them;
        because islands are ringed by water the fill can never leave the rect."""
        lx, ly, lw, lh = self.islands[island]
        x1, y1 = min(self.width, lx + lw), min(self.height, ly + lh)
        tiles = self.tiles
        WALL, WATER, WINDOW = self.WALL, self.WATER, self.WINDOW

        regions: dict[tuple[int, int], int] = {}
        region_id = 0
        for y in range(ly, y1):
            for x in range(lx, x1):
                if (x, y) in regions:
                    continue
                t = tiles[y][x]
                if t == WALL or t == WATER or t == WINDOW:
                    continue
                region_id += 1
                queue: deque[tuple[int, int]] = deque([(x, y)])
                regions[(x, y)] = region_id
                # Inlined neighbour/walkability scan (hot flood-fill); mirrors
                # find_path / distance_field for the same reason.
                while queue:
                    cx, cy = queue.popleft()
                    for nx, ny in (
                        (cx + 1, cy), (cx - 1, cy), (cx, cy + 1), (cx, cy - 1),
                        (cx + 1, cy + 1), (cx + 1, cy - 1), (cx - 1, cy + 1), (cx - 1, cy - 1),
                    ):
                        if not (lx <= nx < x1 and ly <= ny < y1):
                            continue
                        if (nx, ny) in regions:
                            continue
                        nt = tiles[ny][nx]
                        if nt == WALL or nt == WATER or nt == WINDOW:
                            continue
                        regions[(nx, ny)] = region_id
                        queue.append((nx, ny))
        return regions

    def region_of(self, x: int, y: int) -> int | None:
        """The connected-region id of a walkable tile, or ``None`` if the tile isn't
        walkable. Labels are cached per island and rebuilt only when that island is
        edited, so a build on one island doesn't invalidate the other 99."""
        island = self._island_index_of(x, y)
        if island is None:
            return None
        edit_rev = self._island_edit_rev.get(island, 0)
        if self._island_region_rev.get(island) != edit_rev:
            self._island_region_cache[island] = self._compute_island_regions(island)
            self._island_region_rev[island] = edit_rev
        local = self._island_region_cache[island].get((x, y))
        return None if local is None else island * self._REGION_ID_STRIDE + local

    def same_region(self, a: tuple[int, int], b: tuple[int, int]) -> bool:
        """True when both tiles are walkable and mutually reachable on foot -- a
        cheap stand-in for ``find_path`` when you only need reachability."""
        ra = self.region_of(a[0], a[1])
        return ra is not None and ra == self.region_of(b[0], b[1])

    def enclosed_rooms(self, max_size: int = 400) -> list[frozenset[tuple[int, int]]]:
        """All enclosed house interiors across the world, cached per island and
        rebuilt only for islands edited since the last call (see ``set_tile``). A
        build on one island no longer re-floods the other 99 -- the whole-map
        re-detection was a top per-turn cost at archipelago scale."""
        changed = self._all_rooms_cache is None
        for idx, rect in enumerate(self.islands):
            rev = self._island_edit_rev.get(idx, 0)
            if self._island_rooms_rev.get(idx) != rev or idx not in self._island_rooms_cache:
                self._island_rooms_cache[idx] = self.find_enclosed_rooms(max_size, bounds=rect)
                self._island_rooms_rev[idx] = rev
                changed = True
        if changed:
            rooms: list[frozenset[tuple[int, int]]] = []
            for idx in range(len(self.islands)):
                rooms.extend(self._island_rooms_cache[idx])
            self._all_rooms_cache = rooms
        return self._all_rooms_cache

    def find_enclosed_rooms(
        self,
        max_size: int = 400,
        bounds: tuple[int, int, int, int] | None = None,
    ) -> list[frozenset[tuple[int, int]]]:
        """Return the interiors of enclosed rooms: floor regions sealed off by
        walls/windows whose only openings are doors.

        A region qualifies as a house interior when it (a) never touches the map
        border, (b) is bounded by wall/window/door tiles, and (c) is reachable
        from outside only through at least one door. The flood-fill spreads over
        floor tiles only, so walls, windows, water, and doors all act as
        boundaries -- a doorway stops the fill, which is what keeps a house's
        inside from leaking out into the open map.

        ``bounds`` (an ``(x0, y0, w, h)`` land rect) restricts the seed scan to one
        island; because islands are ringed by water the floor flood can't escape it,
        so a scoped scan yields exactly that island's rooms. Prefer the cached
        ``enclosed_rooms`` over calling this directly per turn.
        """
        rooms: list[frozenset[tuple[int, int]]] = []
        visited: set[tuple[int, int]] = set()

        if bounds is None:
            x0, y0, x1, y1 = 0, 0, self.width, self.height
        else:
            bx, by, bw, bh = bounds
            x0, y0 = max(0, bx), max(0, by)
            x1, y1 = min(self.width, bx + bw), min(self.height, by + bh)

        for sy in range(y0, y1):
            for sx in range(x0, x1):
                if (sx, sy) in visited or self.tiles[sy][sx] != self.FLOOR:
                    continue

                region: list[tuple[int, int]] = []
                touches_border = False
                has_door = False
                queue: deque[tuple[int, int]] = deque([(sx, sy)])
                visited.add((sx, sy))

                while queue:
                    cx, cy = queue.popleft()
                    region.append((cx, cy))
                    if cx == 0 or cy == 0 or cx == self.width - 1 or cy == self.height - 1:
                        touches_border = True
                    for nx, ny in self.neighbors_4(cx, cy):
                        neighbor_tile = self.tiles[ny][nx]
                        if neighbor_tile == self.DOOR:
                            has_door = True
                            continue
                        if neighbor_tile != self.FLOOR:
                            continue
                        if (nx, ny) in visited:
                            continue
                        visited.add((nx, ny))
                        queue.append((nx, ny))
                    if len(region) > max_size:
                        break

                if not touches_border and has_door and len(region) <= max_size:
                    rooms.append(frozenset(region))

        return rooms

    def neighbors_4(self, x: int, y: int) -> list[tuple[int, int]]:
        candidates = [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
        return [(nx, ny) for nx, ny in candidates if self.in_bounds(nx, ny)]

    def neighbors_8(self, x: int, y: int) -> list[tuple[int, int]]:
        candidates = [
            (x + 1, y),
            (x - 1, y),
            (x, y + 1),
            (x, y - 1),
            (x + 1, y + 1),
            (x + 1, y - 1),
            (x - 1, y + 1),
            (x - 1, y - 1),
        ]
        return [(nx, ny) for nx, ny in candidates if self.in_bounds(nx, ny)]

    def line_points(self, start: tuple[int, int], end: tuple[int, int]) -> list[tuple[int, int]]:
        """Return Bresenham line points from start to end, inclusive."""
        x0, y0 = start
        x1, y1 = end

        points: list[tuple[int, int]] = []
        dx = abs(x1 - x0)
        dy = abs(y1 - y0)
        sx = 1 if x0 < x1 else -1
        sy = 1 if y0 < y1 else -1

        err = dx - dy

        while True:
            points.append((x0, y0))
            if x0 == x1 and y0 == y1:
                break

            e2 = 2 * err
            if e2 > -dy:
                err -= dy
                x0 += sx
            if e2 < dx:
                err += dx
                y0 += sy

        return points

    def has_line_of_sight(self, start: tuple[int, int], end: tuple[int, int]) -> bool:
        if not self.in_bounds(start[0], start[1]) or not self.in_bounds(end[0], end[1]):
            return False

        points = self.line_points(start, end)
        for x, y in points[1:-1]:
            if self.tile_at(x, y) == self.WALL:
                return False
        return True

    def find_path(
        self,
        start: tuple[int, int],
        goal: tuple[int, int],
        blocked_tiles: set[tuple[int, int]] | None = None,
    ) -> list[tuple[int, int]]:
        """Find a shortest 8-way path from start to goal using A*.

        Returns a list of coordinates excluding start and including goal.
        Returns [] when no path exists.

        Movement is 8-directional at unit cost (a diagonal step costs the same as
        a cardinal one), so the fewest-steps distance across open ground is the
        Chebyshev distance ``max(|dx|, |dy|)``. That makes Chebyshev an admissible
        *and* consistent heuristic: A* returns a path of the same length a plain
        BFS would, but expands far fewer tiles because it walks toward the goal
        instead of flooding outward in all directions. The neighbour scan, bounds
        test and walkability test are inlined here (rather than going through
        ``neighbors_8``/``is_walkable``) because this is the hot loop -- it avoids
        building a fresh candidate list and a method call per tile touched.
        """
        if start == goal:
            return []
        sx, sy = start
        gx, gy = goal
        width, height = self.width, self.height
        if not (0 <= sx < width and 0 <= sy < height):
            return []
        if not (0 <= gx < width and 0 <= gy < height):
            return []

        blocked = blocked_tiles or ()
        tiles = self.tiles
        WALL, WATER, WINDOW = self.WALL, self.WATER, self.WINDOW

        # Priority queue of (f = g + heuristic, -g, tile). ``g_score`` doubles as
        # the visited set and supports the lazy "decrease-key" (a tile popped with
        # a g worse than its recorded best is a stale duplicate and is skipped).
        # The second key is ``-g`` so that, among tiles with equal f, the one with
        # the *larger* g (deeper, i.e. nearer the goal) is expanded first. Unit-cost
        # 8-way movement produces wide plateaus of equal-f tiles; breaking ties
        # toward the goal collapses them and cuts expansions by roughly another 10x.
        # It never changes the path's cost -- we stop at the first pop of the goal
        # and the heuristic is consistent -- only which equal-length route is
        # chosen and how few tiles get touched getting there.
        open_heap: list[tuple[int, int, tuple[int, int]]] = [
            (max(abs(sx - gx), abs(sy - gy)), 0, start)
        ]
        came_from: dict[tuple[int, int], tuple[int, int] | None] = {start: None}
        g_score: dict[tuple[int, int], int] = {start: 0}

        while open_heap:
            _f, neg_g, current = heapq.heappop(open_heap)
            if current == goal:
                break
            g = -neg_g
            if g > g_score[current]:
                continue  # stale entry left behind by a later, cheaper push
            cx, cy = current
            ng = g + 1
            for nx, ny in (
                (cx + 1, cy), (cx - 1, cy), (cx, cy + 1), (cx, cy - 1),
                (cx + 1, cy + 1), (cx + 1, cy - 1), (cx - 1, cy + 1), (cx - 1, cy - 1),
            ):
                if not (0 <= nx < width and 0 <= ny < height):
                    continue
                t = tiles[ny][nx]
                if t == WALL or t == WATER or t == WINDOW:
                    continue
                nxt = (nx, ny)
                if nxt in blocked and nxt != goal:
                    continue
                prev = g_score.get(nxt)
                if prev is not None and prev <= ng:
                    continue
                g_score[nxt] = ng
                came_from[nxt] = current
                heapq.heappush(open_heap, (ng + max(abs(nx - gx), abs(ny - gy)), -ng, nxt))

        if goal not in came_from:
            return []

        path: list[tuple[int, int]] = []
        cur: tuple[int, int] | None = goal
        while cur is not None and cur != start:
            path.append(cur)
            cur = came_from[cur]

        path.reverse()
        return path
